name: Deploy to WordPress.org
on:
  workflow_dispatch:
  # push:
  #   tags:
  #   - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build plugin
        run: |
          chmod +x ./release.sh
          ./release.sh

      - name: Deploy to WP.org
        uses: 10up/action-wordpress-plugin-deploy@v2
        with:
          dry-run: true
          generate-zip: false
        env:
          SVN_USERNAME: test
          SVN_PASSWORD: test
          BUILD_DIR: ./releases/subscription
          VERSION: 2.0.0
